- tools/readme.txt
After running `ant` and having it successfully completing, without generating either a `bin` or a `build` directory a few times, I tried `ant build` and got it to generate the `build` directory.
Perhaps this is obvious to a seasoned Java developer, but to a neophyte to Java build systems like myself, adding this precision of documentation might be a nice touch ^.^
> Tiny change to get paths correct and ant tasks generating build directories

- tools/src/wyvern/target/corewyvernIL/decl/DefDeclaration.java
- tools/src/wyvern/target/corewyvernIL/expression/New.java
- tools/src/wyvern/target/corewyvernIL/expression/ObjectValue.java
- tools/src/wyvern/target/corewyvernIL/expression/Variable.java
- tools/src/wyvern/target/corewyvernIL/support/EmptyValContext.java
- tools/src/wyvern/target/corewyvernIL/support/EvalContext.java
- tools/src/wyvern/target/corewyvernIL/support/GenUtil.java
- tools/src/wyvern/target/corewyvernIL/support/VarEvalContext.java
- tools/src/wyvern/tools/tests/ILTests.java
- tools/src/wyvern/tools/typedAST/core/Sequence.java
Evaluation is now supported for multiple modules.
In the test multipleModuleTest, genExp method can generate IL Expression from IL declarations generated from multiple modules. 
genExp generate Expression from Declarations by creating a sequence of let expression.
Then it can be typechecked and evaluated. To support dynamic scoping, a new field was added into Class ObjectValue so that it can store the context while interpreting from new statement. Furthermore, to support this, another method combine was added in EvalContext which can combine two EvalContext together into one.
> Evaluation supported

- tools/src/wyvern/target/corewyvernIL/expression/FieldGet.java
- tools/src/wyvern/target/corewyvernIL/expression/New.java
- tools/src/wyvern/tools/tests/ILTests.java
These commits do two things:
- Replace a bunch of the RuntimeExceptions thrown during typechecking with ToolError.reportError.
- Add a bunch of test cases in ILTests.
Many of the test cases are programs which are not well-typed and expect ToolErrors to be thrown. The purpose is to make sure the errors are reported at compile-time instead of run-time. The tests are:
The other test reads from a val declaration. This one reads from a var declaration.
Tries to write a String to a field declared as an Int. Appropriately throws a ToolError.
Tries to write to an Int declared with val. Appropriately throws a ToolError.
Declares two objects with mutable Int fields. Tries to assign one Int field to the other. Currently gives a ClassCastException during interpretation.
This test tries to read from a …
> Add ILTests, replace RuntimeExceptions with ToolError.reportError

- tools/src/wyvern/tools/parsing/coreparser/ASTBuilder.java
- tools/src/wyvern/tools/parsing/coreparser/WyvernASTBuilder.java
- tools/src/wyvern/tools/parsing/coreparser/WyvernParser.jj
- tools/src/wyvern/tools/tests/ILTests.java
This guy adds a sugar for representing parameter and return types.
For example, `val identity: system.Int->system.Int = (x: system.Int) => x\n` creates a lambda function that returns it's argument. Note the Haskell-esque arrow sugar on the left hand side of the assignment. That's the sugar added by this commit.
> Adding in an arrow sugar for function types

- tools/src/wyvern/target/corewyvernIL/decl/Declaration.java
- tools/src/wyvern/target/corewyvernIL/decl/DefDeclaration.java
- tools/src/wyvern/target/corewyvernIL/decl/DelegateDeclaration.java
- tools/src/wyvern/target/corewyvernIL/decl/TypeDeclaration.java
- tools/src/wyvern/target/corewyvernIL/decl/ValDeclaration.java
- tools/src/wyvern/target/corewyvernIL/decl/VarDeclaration.java
- tools/src/wyvern/target/corewyvernIL/expression/AbstractValue.java
- tools/src/wyvern/target/corewyvernIL/expression/Bind.java
- tools/src/wyvern/target/corewyvernIL/expression/BooleanLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/Cast.java
- tools/src/wyvern/target/corewyvernIL/expression/Expression.java
- tools/src/wyvern/target/corewyvernIL/expression/FieldGet.java
- tools/src/wyvern/target/corewyvernIL/expression/FieldSet.java
- tools/src/wyvern/target/corewyvernIL/expression/IExpr.java
- tools/src/wyvern/target/corewyvernIL/expression/IntegerLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/JavaValue.java
- tools/src/wyvern/target/corewyvernIL/expression/Let.java
- tools/src/wyvern/target/corewyvernIL/expression/Literal.java
- tools/src/wyvern/target/corewyvernIL/expression/Match.java
- tools/src/wyvern/target/corewyvernIL/expression/MethodCall.java
- tools/src/wyvern/target/corewyvernIL/expression/New.java
- tools/src/wyvern/target/corewyvernIL/expression/RationalLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/StringLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/Variable.java
- tools/src/wyvern/tools/tests/FreeVars.java
This attempts to solve #76 
A getFreeVariables() method has been declared in the following places:
* corewyvernIL.expression.Expression
* corewyvernIL.expression.IExpr (this one is needed for FieldSet and FieldGet, which contain IExpr fields as well as regular Expression fields)
* corewyvernIL.decl.Declaration
There are some tests in a new FreeVars file which tests the new functions out on a few code fragments.
> Free Variables

- tools/src/wyvern/target/corewyvernIL/expression/MethodCall.java
- tools/src/wyvern/tools/tests/ILTests.java
Hi there!
The first test I added, `testDependentType2`, checks to make sure that you can have dependently typed arguments. As I noted in my last PR https://github.com/wyvernlang/wyvern/pull/79 , dependent types could only be used as return values until this PR. I made changes to https://github.com/wyvernlang/wyvern/blob/a2d0b661f6e0540ae6be8ea539c0f2da74805378/tools/src/wyvern/target/corewyvernIL/expression/MethodCall.java to get that test to pass.
After, using the new dependent types, I wrote a pure-Wyvern `if-else` construct. The two tests pass.
However, note that my `if Body` construct has a type member of `system.Int`. This limits the if statement to only return `int`s :sob: 
The reason for this is that abstract type members aren't implemented yet, so I could say write this, for …
> adding a test for if statements

- tools/src/wyvern/target/corewyvernIL/expression/BooleanLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/IntegerLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/JavaValue.java
- tools/src/wyvern/target/corewyvernIL/expression/Let.java
- tools/src/wyvern/target/corewyvernIL/expression/Match.java
- tools/src/wyvern/target/corewyvernIL/expression/New.java
- tools/src/wyvern/target/corewyvernIL/expression/ObjectValue.java
- tools/src/wyvern/target/corewyvernIL/expression/RationalLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/StringLiteral.java
- tools/src/wyvern/target/corewyvernIL/expression/Value.java
- tools/src/wyvern/target/corewyvernIL/expression/Variable.java
- tools/src/wyvern/target/corewyvernIL/support/EmptyGenContext.java
- tools/src/wyvern/target/corewyvernIL/support/EmptyTypeContext.java
- tools/src/wyvern/target/corewyvernIL/support/EmptyValContext.java
- tools/src/wyvern/target/corewyvernIL/support/EvalContext.java
- tools/src/wyvern/target/corewyvernIL/support/GenContext.java
- tools/src/wyvern/target/corewyvernIL/support/GenUtil.java
- tools/src/wyvern/target/corewyvernIL/support/MethodGenContext.java
- tools/src/wyvern/target/corewyvernIL/support/TypeContext.java
- tools/src/wyvern/target/corewyvernIL/support/TypeGenContext.java
- tools/src/wyvern/target/corewyvernIL/support/Util.java
- tools/src/wyvern/target/corewyvernIL/support/VarBindingContext.java
- tools/src/wyvern/target/corewyvernIL/support/VarEvalContext.java
- tools/src/wyvern/target/corewyvernIL/support/VarGenContext.java
- tools/src/wyvern/tools/typedAST/core/binding/NameBindingImpl.java
- tools/src/wyvern/tools/typedAST/core/declarations/ModuleDeclaration.java
- tools/src/wyvern/tools/typedAST/core/expressions/Invocation.java
- tools/src/wyvern/tools/typedAST/core/expressions/Match.java
This links two classes which are used for different purposes, but are related in structure and content. Adding a getType method to the Value interface allows the type of a variable to be looked up from an EvalContext, so an EvalContext can now be used anywhere a TypeContext is needed.
> Make EvalContext extend TypeContext

- tools/src/wyvern/tools/tests/ILTests.java
Run tests using the standard gen context, so now the correct ToolError is thrown
> Fix broken tests

- tools/src/wyvern/target/corewyvernIL/support/CallableExprGenerator.java
- tools/src/wyvern/target/corewyvernIL/support/DefaultExprGenerator.java
- tools/src/wyvern/target/corewyvernIL/support/InvocationExprGenerator.java
- tools/src/wyvern/tools/typedAST/core/expressions/Application.java
As per our conversation, I refactored the `CallableExpression` interface to return the `DefDeclType` instead of the `List<FormalArg>`
> Refactor interface to expose DefDeclType

- tools/src/wyvern/lib/examples/logging/files.wyv
- tools/src/wyvern/lib/examples/logging/logApplication.wyv
- tools/src/wyvern/lib/examples/logging/logClient.wyv
- tools/src/wyvern/lib/examples/logging/logging.wyv
- tools/src/wyvern/stdlib/FileIO.java
- tools/src/wyvern/target/corewyvernIL/expression/FieldGet.java
- tools/src/wyvern/target/corewyvernIL/expression/MethodCall.java
- tools/src/wyvern/target/corewyvernIL/type/StructuralType.java
- tools/src/wyvern/tools/errors/ErrorMessage.java
Made the logging example in section 2 of the Wyvern guide to work without the use of resource modules. This required modifying typechecking of method calls on Java objects to account for method overloading.
> Working logging example in section 2 of Wyvern guide

- tools/src/wyvern/tools/errors/ErrorMessage.java
- tools/src/wyvern/tools/lexing/WyvernLexer.x
If the last character is a backslash (e.g. "abc\") which is not a part of an escape sequence, then I wasn't reporting an error.
> Fixed a bug in the handling of escape sequences

- tools/build.xml
- tools/checkstyle.xml
- tools/src/wyvern/tools/typedAST/core/expressions/New.java
TL;DR I added some pretty straightforward Checkstyle rules and an Ant task to lint files. Then I removed ~80 lint violations.
More details:
I took the [sample Checkstyle configuration](http://checkstyle.sourceforge.net/google_style.html) from the [Google Java styleguide](http://google.github.io/styleguide/javaguide.html). Then, I removed a couple of lints that didn't feel right for our particular project.
IMHO there's no reasonable way for us to just "turn on" linting on our builds. We have far too many violations for that to be useful. To be specific, we have 77,590 lint violations in our project, and linting takes 8 seconds if writing the violations to disk and 16 seconds if printing the violations to the terminal.
Instead, I'd like to incrementally remove the lint. I propose we make a …
> Checkstyle

- tools/src/wyvern/target/corewyvernIL/astvisitor/EmitOIRState.java
- tools/src/wyvern/target/corewyvernIL/astvisitor/EmitOIRVisitor.java
Encapsulate public variables, remove some unused code/comments, putting variable declarations at the place where they get used, other minor stuff like that.
BTW: if possible, could @JonathanAldrich or @RobbieMcKinstry give me a quick rundown on what the OIR classes are? (And also what OIR stands for)
> Reformat OIR classes

- tools/build.xml
- tools/src/wyvern/tools/typedAST/core/expressions/Application.java
I wasn't able to directly cherry-pick over the diff from the other branch, but I reproduced the changes manually. Not the cleanest I could make it, but it's an improvement.
Also, the linter is not hooked into `ant build` properly (I think I noticed this when working on the dead code removal) so it doesn't actually enforce that the files remain lint-free. I'll patch this as soon as I get a chance; for a patch to pass tests, I also have to remove all of the lints, so the PR won't be a one-liner.
- R
> Refactor application genIL to reduce complexity

- tools/src/wyvern/target/oir/EmitPythonVisitor.java
- tools/src/wyvern/tools/tests/OIRTests.java
- tools/src/wyvern/tools/typedAST/core/declarations/DefDeclaration.java
- tools/src/wyvern/tools/typedAST/core/declarations/VarDeclaration.java
- tools/src/wyvern/tools/typedAST/core/expressions/Assignment.java
- tools/src/wyvern/tools/util/GetterAndSetterGeneration.java
Addresses #138
Suppose you have an object with a var field like this:
```
val obj = new
var x : Int = 0
```
When generating Wyvern IL code this is turned into the following object:
```
val obj = new
var x: Int = 0
def setX(y: Int): Unit =
this.x = y
def getX(): Int =
this.x
```
When you access a field ala obj.x this is actually turned into obj.getX(). obj.x = y gets turned into obj.setX(y). (Discussion of why this approach is done can be found in #64)
#138 highlights an issue with the auto-generated method names, which is that if an object has a mutable field called x and a user-defined setX, then the auto-generated setX will clash with that. This causes the ToolError in #138.
My P.R. doesn't give a robust solution to the problem. It just mangles the names of the auto-generated …
> Mangle names of auto-generated getters and setters

- tools/src/wyvern/target/corewyvernIL/expression/FieldGet.java
- tools/src/wyvern/target/corewyvernIL/expression/FieldSet.java
- tools/src/wyvern/target/corewyvernIL/expression/MethodCall.java
- tools/src/wyvern/target/corewyvernIL/support/DefaultExprGenerator.java
- tools/src/wyvern/target/corewyvernIL/support/InvocationExprGenerator.java
- tools/src/wyvern/target/corewyvernIL/support/Util.java
- tools/src/wyvern/target/corewyvernIL/transformers/DynCastsTransformer.java
- tools/src/wyvern/tools/tests/ILTests.java
- tools/src/wyvern/tools/typedAST/core/expressions/Application.java
- tools/src/wyvern/tools/typedAST/core/expressions/Assignment.java
- tools/src/wyvern/tools/typedAST/core/expressions/Invocation.java
This P.R. extends the typechecker to permit var/val/method accesses on a dynamic object and adds a bunch of tests to demonstrate that this works.
For example this code:
```
val obj: Dyn = new
val field: Int = 5
obj.field
```
The way it's done is by using a sentinel value of null for InvocationExprGenerator.declType. Unfortunately this means any user of InvocationExprGenerator needs to manually check whether getDeclType returns null.
> Typechecking dynamic objects

- tools/src/wyvern/target/corewyvernIL/expression/Cast.java
- tools/src/wyvern/target/corewyvernIL/expression/FieldSet.java
- tools/src/wyvern/target/corewyvernIL/transformers/DynCastsTransformer.java
- tools/src/wyvern/tools/tests/TransformTests.java
Addresses #87
* Update DynCastsTransformer so it will cast a dynamic receiver to the appropriate type in FieldSet/FieldGet/MethodCall expressions.
* Add a few tests to show the transformation works in some simple examples.
* Add a more complicated example involving nested resources which breaks under DynCastsTransformer--See the issue page for more.
> DynCastsTransformer

- tools/src/wyvern/tools/tests/OIRTests.java
Added a test (marked as CurrentlyBroken) that demonstrates the previously-discussed stack overflow typechecking bug.
> Isolated typechecking infinite loop

- tools/src/wyvern/target/corewyvernIL/astvisitor/ASTVisitor.java
- tools/src/wyvern/target/corewyvernIL/astvisitor/EmitOIRVisitor.java
- tools/src/wyvern/target/corewyvernIL/astvisitor/PlatformSpecializationVisitor.java
- tools/src/wyvern/target/corewyvernIL/astvisitor/TailCallVisitor.java
- tools/src/wyvern/target/corewyvernIL/decl/ModuleDeclaration.java
- tools/src/wyvern/target/corewyvernIL/expression/Bind.java
- tools/src/wyvern/target/corewyvernIL/expression/Let.java
- tools/src/wyvern/target/corewyvernIL/support/ModuleResolver.java
- tools/src/wyvern/target/corewyvernIL/transformers/DynCastsTransformer.java
- tools/src/wyvern/tools/PythonCompiler.java
- tools/src/wyvern/tools/tests/ExampleTests.java
- tools/src/wyvern/tools/typedAST/core/declarations/ImportDeclaration.java
- tools/src/wyvern/tools/typedAST/core/declarations/ModuleDeclaration.java
This is the initial implementation of modules inside the core Wyvern IL.
If M is a module that imports some other platform-dependent module, then M will compile to a ModuleDeclaration in the core IL, rather than a DefDeclaration or a ValDeclaration as before. 
This ModuleDeclaration should be platform-independent.
Then the PlatformSpecializationVisitor takes in a platform and links the ModuleDeclarations with the dependencies on the given platform, and the ModuleDeclarations become DefDeclarations or ValDeclarations.
From this point, compilation proceeds as before.
> Coreil modules

- tools/src/wyvern/tools/tests/TestUtil.java
When trying to run the examples/tsls/postfixClient.wyv file from the command prompt
set to examples as the current directory, we were getting the following exception:
Exception in thread "main" java.lang.RuntimeException: the root path "src/wyvern/tools/tests/" for the module resolver must be a directory
This is a fix for this exception.
> Make paths in TestUtil relative to WYVERN_HOME

- tools/src/wyvern/tools/tests/ILTests.java
As of commit 4447baf0824558f4ae76dc6c3e43a7fd5ca2d473, the ILTests.testNestedDecl() works. Removed the "CurrentlyBroken" annotation to include the test into the regression test suite.
After this PR is accepted, https://github.com/wyvernlang/wyvern/issues/135 can be closed.
> Includes the ILTests.testNestedDecl() test again since it now works

- tools/src/wyvern/tools/tests/ILTests.java
As of commit 4447baf0824558f4ae76dc6c3e43a7fd5ca2d473, the issue described in https://github.com/wyvernlang/wyvern/issues/138 is no longer there. I added a test for this problem to prevent it in the future.
After this PR is accepted, https://github.com/wyvernlang/wyvern/issues/138 can be closed.
> Resolves the object setter issue

- tools/src/wyvern/target/corewyvernIL/astvisitor/PlatformSpecializationVisitor.java
- tools/src/wyvern/target/corewyvernIL/astvisitor/TailCallVisitor.java
- tools/src/wyvern/target/corewyvernIL/decl/DefDeclaration.java
- tools/src/wyvern/target/corewyvernIL/decl/TypeDeclaration.java
- tools/src/wyvern/target/corewyvernIL/decltype/DeclTypeWithResult.java
- tools/src/wyvern/target/corewyvernIL/expression/Match.java
- tools/src/wyvern/target/corewyvernIL/type/RefinementType.java
- tools/src/wyvern/tools/errors/ErrorMessage.java
- tools/src/wyvern/tools/tests/ILTests.java
- tools/src/wyvern/tools/tests/modules/module/lambdaCalc.wyv
- tools/src/wyvern/tools/tests/modules/module/parametrizedList.wyv
- tools/src/wyvern/tools/tests/modules/module/taggedList.wyv
- tools/src/wyvern/tools/typedAST/core/declarations/TypeDeclaration.java
- tools/src/wyvern/tools/typedAST/core/declarations/TypeVarDecl.java
- tools/src/wyvern/tools/typedAST/core/expressions/Case.java
- tools/src/wyvern/tools/typedAST/core/expressions/Match.java
- tools/src/wyvern/tools/typedAST/core/expressions/New.java
- tools/src/wyvern/tools/typedAST/core/expressions/TaggedInfo.java
Summary:
This commit fully implements the simple datatypes from the `typedAST` all the way to interpretation. Right now, no new constructs were added to the `typedAST`; the main difference is that tagging information is carried through in the `TypeDeclaration` which is then translated into the IL as a `DataType`. Existing classes are used to implement pattern matching, but now fully implemented with translation and interpretation. Parametrized datatypes are not currently fully working.
Testing:
This commit contains a few new test cases.
- `taggedList.wyv` passes
- `parametrizedList.wyv` is a wip: the type declarations compile but the pattern matching does not
> Simple algebraic datatype implementation

- tools/src/wyvern/target/corewyvernIL/support/ModuleResolver.java
- tools/src/wyvern/tools/tests/ModuleSystemTests.java
- tools/src/wyvern/tools/tests/modules/circular1.wyv
- tools/src/wyvern/tools/tests/modules/circular2.wyv
- tools/src/wyvern/tools/tests/modules/cyclic/cyclic1a.wyv
- tools/src/wyvern/tools/tests/modules/cyclic/cyclic1b.wyv
- tools/src/wyvern/tools/tests/modules/cyclic/cyclic2a.wyv
- tools/src/wyvern/tools/tests/modules/cyclic/cyclic2b.wyv
- tools/src/wyvern/tools/tests/modules/cyclic/cyclic2c.wyv
- tools/src/wyvern/tools/tests/modules/cyclic/cyclic3a.wyv
This adds a solution for #159. `ModuleResolver` now keeps track of the modules it is trying to resolve at any given point in a field called `modulesBeingResolved`. Before resolving a module, it first checks if that module is already in `modulesBeingResolved`.
I think this turns module resolution into O(M^2), where M = the number of modules, since for every module (O(M) of them) you must check whether it is in `modulesBeingResolved` (also O(M)).
Also adds two more tests which check the following cases:
* a -> b -> c -> a
* a -> b -> c -> b
> Report error when a module has a cyclic dependency

- .travis.yml
- backend/bootstrap.sh
- tools/src/wyvern/tools/BytecodeCompiler.java
- tools/src/wyvern/tools/Interpreter.java
Also fixes compiler/interpreter exit codes.
Travis instances by default only have 4G of RAM. We need at least 6G to bootstrap in a reasonable amount of time. As suggested by the [travis docs](https://docs.travis-ci.com/user/reference/overview/#Virtualisation-Environment-vs-Operating-System), this patch adds `sudo: required` so we get the GCE-based CI servers with 8G of RAM. The damage here is that these instances take longer to boot (20-50s vs 1-6s).
I removed what looks to be an old workaround introduced in 252e5a6b1. Let me know if this should stay.
The patch also adds some code to the bootstrap script which prints '.' every minute so travis doesn't time out builds.
Overall, this increases CI run times from 2min -> 20min. Bootstrapping takes 16m30s on travis.
> Add bootstrapping and backend tests to travis

- backend/examples/tco.wyv
- backend/src/emit_js.wyv
- backend/src/inline_if.wyv
- backend/src/main.wyv
- backend/src/mark_tco.wyv
- backend/src/print_bytecode.wyv
- backend/src/rename.wyv
- backend/src/wyb_ast.wyv
Achieved via a hack which inlines if statements by looking for the
specific CoreWyvernIL pattern emitted by the frontend. Temporary measure
until ifTSL is rewritten as a macro so intermediate methods are not
generated for if arms.
> Allow tail calls through if

- tools/src/wyvern/target/corewyvernIL/modules/Module.java
- tools/src/wyvern/target/corewyvernIL/modules/TypedModuleSpec.java
- tools/src/wyvern/target/corewyvernIL/support/ModuleResolver.java
This pull request fixes the bug that is introduced by adding quantification lifting.
The original cache caches modules by the name of the module. So if a module is both lifted and not lifted, there will be only one copy, instead of two, in the cache. To solve this problem, I created two caches to separately cache lifted and unlifted modules. I also added a private field to TypedModuleSpec of type Module, to avoid resolving module by its qualifiedName.
> Separately cache lifted and unlifted modules

- stdlib/platform/java/fileSystem.wyv
When reading a file in line-by-line, at the end of the file, Java's null was put into Wyvern's Option.
> Fixes a bug in the new Java IO library

- backend/examples/algebra.wyv
- backend/src/emit_js.wyv
- backend/src/main.wyv
- backend/stdlib/support/string.js
- examples/capabilities/SealerUnsealer.wyv
- examples/introductory/algebra.wyv
- stdlib/platform/java/wyvern/String.wyv
- stdlib/wyvern/String.wyt
- tools/src/wyvern/stdlib/Globals.java
- tools/src/wyvern/stdlib/support/StringHelper.java
- tools/src/wyvern/target/corewyvernIL/expression/StringLiteral.java
- tools/src/wyvern/tools/tests/errors/ReturnTypeBug.wyv
- tools/src/wyvern/tools/tests/webarch/database.wyv
Non-static `String` operations should be built-in, i.e. be implemented in [Globals.java](https://github.com/wyvernlang/wyvern/blob/7c795a39245a906c04606b67e7b29294b690dc05/tools/src/wyvern/stdlib/Globals.java) and [StringLiteral.java](https://github.com/wyvernlang/wyvern/blob/7c795a39245a906c04606b67e7b29294b690dc05/tools/src/wyvern/target/corewyvernIL/expression/StringLiteral.java). Static `String` operations should be in a Wyvern module, such as [String.wyv](https://github.com/wyvernlang/wyvern/blob/7c795a39245a906c04606b67e7b29294b690dc05/stdlib/platform/java/wyvern/String.wyv) and [String.wyt](https://github.com/wyvernlang/wyvern/blob/7c795a39245a906c04606b67e7b29294b690dc05/stdlib/wyvern/String.wyt).
> Better organizes String operations

- examples/text-editor/JFrame.wyt
- examples/text-editor/JTextArea.wyt
- examples/text-editor/Logger.wyt
- examples/text-editor/NativeActionCreator.wyt
- examples/text-editor/NativeJOptionPane.wyt
- examples/text-editor/NativeUIManager.wyt
- examples/text-editor/Plugin.wyt
- examples/text-editor/README.md
- examples/text-editor/TextEditor.wyt
- examples/text-editor/log.txt
- examples/text-editor/logger.wyv
- examples/text-editor/main.wyv
- examples/text-editor/plugins/darkTheme.wyv
- examples/text-editor/plugins/lightTheme.wyv
- examples/text-editor/plugins/questionnaireCreator.wyv
- examples/text-editor/plugins/wordCount.wyv
- examples/text-editor/textEditor.wyv
- tools/src/wyvern/stdlib/support/TextEditorHelper.java
See [`README`](https://github.com/wyvernlang/wyvern/compare/text-editor?expand=1#diff-8fd621e94683c9d3a92b6faec83f06d3) for how to use the text-editor application and extend it with plugins.
Currently, the application isn't annotated with effects because 1) it relies on Wyvern code that is currently unannotated (e.g., [`fileSystem`](https://github.com/wyvernlang/wyvern/blob/master/stdlib/platform/java/fileSystem.wyv)) and 2) more discussion is needed about how to associate effects with Java objects.
Also, there are two places (namely, in [`textEditor.wyv`](https://github.com/wyvernlang/wyvern/compare/text-editor?expand=1#diff-ea5e9c364f9de65028a3c7431c40d487) and [`NativeUIManager.wyt`](https://github.com/wyvernlang/wyvern/compare/text-editor?expand=1#diff-7bbe3a73c6723b515a6bae406e5c13c4) …
> Extensible text-editor application with four plugins

- tools/src/wyvern/stdlib/Globals.java
- tools/src/wyvern/target/corewyvernIL/expression/BooleanLiteral.java
- tools/src/wyvern/tools/tests/OIRTests.java
Added boolean comparison operator == and !=, added test cases in OIRTests.java.
> Resolved issue #334, added boolean comparison operator == and !=, added test cases.

- tools/src/wyvern/tools/lexing/WyvernLexer.x
Currently, the lexer's flagTok is not always set for each new (non-empty) line. This causes dslIndents to be sometimes wrongly lexed as regular indents. The following example produces an INCONSISTENT_INDENT error on the last line when it should be legal.
```
type Option = option.Option
if (true)
stdout.print("hello\n")
```
The error is caused by the second line not resetting flagTok from TYPE to null. In this case we cannot manually set flagTok to null in any production rule because we risk overwriting the flagTok set by the builtin keywords of this line (e.g. def, type). The proposed fix adds a boolean member flagTokSet to track whether we manually set flagTok to a non-null value on this line. If not, we should revert it to null when done with this line so that the flagTok from the …
> Fix Lexer flagTok not always reset

- tools/src/wyvern/tools/lexing/WyvernLexer.x
- tools/src/wyvern/tools/tests/LexingTests.java
Currently the lexer does not always reset flagTok from EQARROW to null when "=>" is not the last non-whitespace token. The following code causes the indentation on line 2 to be lexed as a regular indent instead of a dsl indent.
```
if (((x: Int) => x + 1)(2) > 3)
stdout.print("yes")
else
stdout.print("no")
```
The problem is due to [the eqarrow check](https://github.com/wyvernlang/wyvern/blob/92025a284f10eac3e33085a4387e1d60731e1297/tools/src/wyvern/tools/lexing/WyvernLexer.x#L531) requiring the last token in list to not be whitespace, which is true for line 1 in the code snippet above.
The proposed fix uses the isEQARROWlast flag instead for this check. To make this work, adjustEQARROW() is called on every line element to make sure the flag is updated.
~TODO: I will update this PR with …
> Fix EQARROW not resetting flagTok

- examples/optionType.wyv
- tools/src/wyvern/tools/tests/OIRTests.java
- tools/src/wyvern/tools/typedAST/core/declarations/ValDeclaration.java
- tools/src/wyvern/tools/typedAST/core/expressions/Assignment.java
Added examples of implicit type conversion in both example folder and OIRTests. Fixed minor problems regarding option type check. Modified generateOptionTypeExpr function to include MOD.option as a path variable.
> Added examples of implicit type conversion in both example folder and OIRTests. Fixed minor problems regarding option type check.

- examples/optionType.wyv
- tools/src/wyvern/target/corewyvernIL/expression/Variable.java
- tools/src/wyvern/tools/parsing/coreparser/ASTBuilder.java
- tools/src/wyvern/tools/parsing/coreparser/WyvernASTBuilder.java
- tools/src/wyvern/tools/parsing/coreparser/WyvernParser.jj
- tools/src/wyvern/tools/typedAST/core/expressions/Assignment.java
- tools/src/wyvern/tools/typedAST/core/expressions/Variable.java
Support explicit option type conversion from T? to T using "!" operator for val declaration, var declaration and assignment statement. Modified example program optionType.wyv in the example folder.
Supported the follow expression:
```scala
val str: String? = "Hello, Wyvern!"
val str1: String = str! // converted str from String? type to String type in val declaration
var str2: String = str! //  converted str from String? type to String type in var declaration
str2 = str! // converted str from String? type to String type in assignment statement
```
> Support explicit option type conversion from T? to T using "!" operator

- selfhost/binding.wyv
- selfhost/lambda.wyv
- selfhost/raw.wyv
- selfhost/typecheck.wyv
- selfhost/wyvernParser.wyv
I changed the _PLUS_, etc to be "+", "-" in the parser. This means a bunch of cases for each operator for member function declarations need to be added, though.
I'm wondering if the name in bound.Call.name should actually be a Binding instead of a string? Although I'm thinking it would difficult to determine which binding to give it (when constructing the bound.Call expression in binding.wyv), since in the context, there could be multiple bindings to function declarations with the same name.
> adding member function type declarations--now 1+1 can be typed
