tools/src/wyvern/target/corewyvernIL/support/GenContext.java, tools/src/wyvern/target/corewyvernIL/support/GenUtil.java, tools/src/wyvern/tools/parsing/coreparser/ASTBuilder.java, tools/src/wyvern/tools/parsing/coreparser/WyvernASTBuilder.java, tools/src/wyvern/tools/parsing/coreparser/WyvernParser.jj, tools/src/wyvern/tools/typedAST/core/declarations/TypeAbbrevDeclaration.java
Hi professor Jonathan, I've updated the code under your guide.
=> add type abbrev under jonathan's guide

tools/src/wyvern/tools/tests/ModuleSystemTests.java, tools/src/wyvern/tools/tests/modules/Database.wyv, tools/src/wyvern/tools/tests/modules/DatabaseClientBad.wyv, tools/src/wyvern/tools/tests/modules/DatabaseClientGood.wyv, tools/src/wyvern/tools/tests/modules/DatabaseProxy.wyv
Test for accessing members of a module transitively in a way which circumvents authority
=> Add tests for transitive member access

tools/src/wyvern/tools/Interpreter.java, tools/src/wyvern/tools/OldInterpreter.java
Works for simple hello world applications. I'm unsure about more complex code.
https://github.com/wyvernlang/wyvern/issues/44
=> Adding a new interpreter file

tools/src/wyvern/tools/tests/ILTests.java
Currently failing and thus excluded from regression test suite.
=> Added a test case to check that anything with a var field is a resource.

tools/src/wyvern/target/corewyvernIL/expression/New.java, tools/src/wyvern/target/corewyvernIL/type/StructuralType.java, tools/src/wyvern/tools/parsing/coreparser/ASTBuilder.java, tools/src/wyvern/tools/parsing/coreparser/WyvernASTBuilder.java, tools/src/wyvern/tools/parsing/coreparser/WyvernParser.jj, tools/src/wyvern/tools/tests/ILTests.java, tools/src/wyvern/tools/typedAST/core/declarations/VarDeclaration.java, tools/src/wyvern/tools/typedAST/core/expressions/New.java
3.5 separate pieces of functionality.
=> Repeat PR #72; fix from Feb 15 meeting; vars in types.

tools/build.xml, tools/src/wyvern/target/corewyvernIL/astvisitor/EmitOIRVisitor.java, tools/src/wyvern/target/oir/PrettyPrintVisitor.java, tools/src/wyvern/tools/tests/OIRTests.java, tools/src/wyvern/tools/tests/suites/AntRegressionTestSuite.java
This pull request adds support for pretty-printing limited parts of the OIR as python. It also fixes a few bugs in the corewyvernIL --> OIR translation step.
=> Basic Python Pretty-printing

tools/src/wyvern/target/corewyvernIL/support/InvocationExprGenerator.java, tools/src/wyvern/target/corewyvernIL/type/NominalType.java, tools/src/wyvern/tools/tests/ILTests.java, tools/src/wyvern/tools/typedAST/core/declarations/DefDeclaration.java, tools/src/wyvern/tools/typedAST/core/declarations/TypeVarDecl.java
Adds support for simple dependent types.
=> Dependent typing

tools/src/wyvern/target/corewyvernIL/decl/DefDeclaration.java, tools/src/wyvern/target/corewyvernIL/decltype/AbstractTypeMember.java, tools/src/wyvern/tools/parsing/coreparser/WyvernParser.jj, tools/src/wyvern/tools/tests/ILTests.java, tools/src/wyvern/tools/typedAST/core/declarations/TypeAbbrevDeclaration.java
Adjusted tests to use the new format
Implemented parsing, AST and typechecking
changes pass new tests.
=> Implementing Abstract Type Members

bin/wyvern
This is a very simple change. Modified the script to use the correct classpath and to determine WYVERN_HOME correctly even when the script location has been added to the PATH.
=> wyvern script modification

tools/src/wyvern/stdlib/Globals.java, tools/src/wyvern/target/corewyvernIL/expression/IntegerLiteral.java, tools/src/wyvern/tools/lexing/WyvernLexer.x, tools/src/wyvern/tools/parsing/coreparser/WyvernParser.jj
Added support for the remainder(%) operator
=> Added support for remainder operator

tools/build.xml, tools/src/wyvern/tools/typedAST/core/expressions/New.java
I condensed a lot of the code in New.typecheck into a lot smaller, more understandable methods. It's still not perfect, but it's marginally cleaner than where it was before.
=> Refactor new

tools/src/wyvern/target/corewyvernIL/VarBinding.java, tools/src/wyvern/target/corewyvernIL/astvisitor/EmitOIRVisitor.java, tools/src/wyvern/target/corewyvernIL/decl/DefDeclaration.java, tools/src/wyvern/target/corewyvernIL/decl/TypeDeclaration.java, tools/src/wyvern/target/corewyvernIL/decl/ValDeclaration.java, tools/src/wyvern/target/corewyvernIL/expression/Bind.java, tools/src/wyvern/target/corewyvernIL/expression/Cast.java, tools/src/wyvern/target/corewyvernIL/expression/FieldSet.java, tools/src/wyvern/target/corewyvernIL/expression/Let.java, tools/src/wyvern/target/corewyvernIL/expression/MethodCall.java, tools/src/wyvern/target/corewyvernIL/support/CallableExprGenerator.java, tools/src/wyvern/target/corewyvernIL/support/DefaultExprGenerator.java, tools/src/wyvern/target/corewyvernIL/support/GenContext.java, tools/src/wyvern/target/corewyvernIL/support/InvocationExprGenerator.java, tools/src/wyvern/target/corewyvernIL/support/TopLevelContext.java, tools/src/wyvern/tools/tests/FFITests.java, tools/src/wyvern/tools/tests/ILTests.java, tools/src/wyvern/tools/tests/ModuleSystemTests.java, tools/src/wyvern/tools/tests/OIRTests.java, tools/src/wyvern/tools/typedAST/core/Sequence.java, tools/src/wyvern/tools/typedAST/core/declarations/ModuleDeclaration.java, tools/src/wyvern/tools/typedAST/core/declarations/TypeVarDecl.java, tools/src/wyvern/tools/typedAST/core/expressions/Application.java, tools/src/wyvern/tools/typedAST/core/expressions/Assignment.java, tools/src/wyvern/tools/typedAST/core/expressions/Fn.java, tools/src/wyvern/tools/typedAST/core/expressions/Invocation.java, tools/src/wyvern/tools/typedAST/core/expressions/Variable.java, tools/src/wyvern/tools/typedAST/interfaces/ExpressionAST.java, tools/src/wyvern/tools/types/QualifiedType.java
Generalise all uses of Expression to IExpr, where possible
=> Generalise to IExpr

tools/build.xml, tools/checkstyle.xml, tools/src/wyvern/tools/typedAST/core/expressions/Application.java, tools/src/wyvern/tools/typedAST/core/expressions/Assignment.java, tools/src/wyvern/tools/typedAST/core/expressions/Case.java, tools/src/wyvern/tools/typedAST/core/expressions/Fn.java, tools/src/wyvern/tools/typedAST/core/expressions/IfExpr.java, tools/src/wyvern/tools/typedAST/core/expressions/Instantiation.java, tools/src/wyvern/tools/typedAST/core/expressions/Invocation.java, tools/src/wyvern/tools/typedAST/core/expressions/Variable.java
I removed probably a thousand lint violations from about half of the TypedAST expressions.
=> Lint Much of the AST

bin/wypy, bin/wyvern, tools/src/wyvern/target/corewyvernIL/astvisitor/EmitOIRVisitor.java, tools/src/wyvern/target/oir/PrettyPrintVisitor.java, tools/src/wyvern/tools/PythonCompiler.java, tools/src/wyvern/tools/tests/OIRTests.java
When running under /bin/sh, the variable $BASH_SOURCE is not guaranteed to exist.
=> Fixed several bugs in Python backend

.gitignore, examples/pong/pong.wyv, examples/pong/pygame.wyv, tools/src/wyvern/stdlib/Globals.java, tools/src/wyvern/target/corewyvernIL/expression/IntegerLiteral.java, tools/src/wyvern/target/oir/EmitPythonVisitor.java, tools/src/wyvern/target/oir/NameMangleVisitor.java, tools/src/wyvern/tools/tests/OIRTests.java, tools/src/wyvern/tools/typedAST/core/expressions/Invocation.java
This pull request fixes several bugs in Python codegen triggered when a Wyvern module is imported
Additionally, integer negation is also implemented.
The pong example is updated to make use of these new features.
=> Fix Python codegen when importing Wyvern modules

tools/src/wyvern/tools/tests/RossettaCodeTests.java, tools/src/wyvern/tools/tests/rosetta/insertion-sort.wyv
defined insertion sort on the list type from collections.
=> adding rosetta example

tools/src/wyvern/target/corewyvernIL/decltype/DefDeclType.java, tools/src/wyvern/tools/errors/ErrorMessage.java, tools/src/wyvern/tools/tests/ILTests.java, tools/src/wyvern/tools/typedAST/core/expressions/Application.java
Allows multiple generic types to be inferred at once.
=> Type inference

examples/rosetta/check-palindrome.wyv, tools/src/wyvern/tools/tests/ExampleTests.java
check-palindrome.wyv in examples/rosetta
=> add check-palindrome example and its junit test

tools/src/wyvern/stdlib/Globals.java, tools/src/wyvern/target/corewyvernIL/decltype/EffectDeclType.java, tools/src/wyvern/target/corewyvernIL/effects/EffectSet.java, tools/src/wyvern/tools/tests/EffectSystemTests.java, tools/src/wyvern/tools/tests/effects/FileIO1.wyt, tools/src/wyvern/tools/tests/effects/FileIO2.wyt, tools/src/wyvern/tools/tests/effects/fileIO1.wyv, tools/src/wyvern/tools/tests/effects/fileIO2.wyv, tools/src/wyvern/tools/tests/effects/fileIOEffects.wyv, tools/src/wyvern/tools/tests/effects/testFileIO1.wyv, tools/src/wyvern/tools/tests/effects/testFileIO2.wyv, tools/src/wyvern/tools/typedAST/core/declarations/DefDeclaration.java, tools/src/wyvern/tools/typedAST/core/declarations/EffectDeclaration.java
- Fixed a bug in checking for recursively defined effects
- Added system.ffiEffect
- Added a couple of tests
=> Some work on effects

examples/io-lib/client.wyv, examples/io-lib/server.wyv, tools/src/wyvern/target/corewyvernIL/type/StructuralType.java, tools/src/wyvern/tools/Interpreter.java, tools/src/wyvern/tools/errors/FileLocation.java, tools/src/wyvern/tools/errors/ToolError.java, tools/src/wyvern/tools/parsing/coreparser/WyvernParser.jj, tools/src/wyvern/tools/tests/ExampleTests.java, tools/src/wyvern/tools/tests/TestUtil.java
Improved some of the messages about nested TSL blocks and displayed
line and column numbers more clearly for newcomers. Closed #186.
=> Fixing io lib bug and errors

tools/src/wyvern/tools/tests/ModuleSystemTests.java, tools/src/wyvern/tools/tests/modules/simpleADTdriver2.wyv, tools/src/wyvern/tools/tests/modules/simpleADTdriver3.wyv, tools/src/wyvern/tools/typedAST/core/declarations/ImportDeclaration.java
=> Implements 'import' and 'require' renaming using 'as'

examples/tsls/lexer.wyv, examples/tsls/parser.wyv, examples/tsls/postfix.wyv, stdlib/prelude.wyv, stdlib/wyvern/collections/list.wyv, stdlib/wyvern/collections/map.wyv, stdlib/wyvern/internal/list.wyv, stdlib/wyvern/option.wyv, stdlib/wyvern/util/matching/regex.wyv, tools/src/wyvern/stdlib/Globals.java, tools/src/wyvern/stdlib/support/Regex.java, tools/src/wyvern/tools/tests/ILTests.java, tools/src/wyvern/tools/tests/ILTestsWithPrelude.java, tools/src/wyvern/tools/tests/OIRTests.java, tools/src/wyvern/tools/tests/suites/AntRegressionTestSuite.java, tools/src/wyvern/tools/tests/tsls/FailingTSL.wyt, tools/src/wyvern/tools/tests/tsls/TrivialTSL.wyt, tools/src/wyvern/tools/tests/tsls/cleanIf.wyv, tools/src/wyvern/tools/tests/tsls/lexer.wyv, tools/src/wyvern/tools/tests/tsls/parser.wyv, tools/src/wyvern/tools/tests/tsls/postfix.wyv, tools/src/wyvern/tools/tests/tsls/testParser.wyv, tools/src/wyvern/tools/tests/webarch/database.wyv
implemented parameterized option in the standard library (and a couple of other minor improvements)
=> Parameterized option

examples/introductory/algebra.wyv, examples/introductory/floats.wyv, stdlib/platform/java/wyvern/String.wyv, stdlib/wyvern/Float.wyv, stdlib/wyvern/String.wyt, tools/src/wyvern/stdlib/support/Float.java, tools/src/wyvern/stdlib/support/StringHelper.java, tools/src/wyvern/target/corewyvernIL/support/GenUtil.java, tools/src/wyvern/tools/tests/ExampleTests.java
This pull request also contains a couple of minor additions to the standard library to make the CAS example possible.
=> Add simple computer algebra system example

backend/src/emit_js.wyv
Makes self-hosting ~9% faster.
Should merge cleanly with  #263.
=> JS Codegen: place methods on object prototype

tools/src/wyvern/target/corewyvernIL/Case.java, tools/src/wyvern/tools/errors/ErrorMessage.java
Adds line number and fixes reason
=> Improve CASE_TYPE_MISMATCH error message

tools/src/wyvern/stdlib/support/PostParameters.java
Fixes a bug in the Java version of the web server implementation. The bug caused a null-pointer exception to be thrown when reading a header of a POST request.
Also, removes unused local variables and orders imports in the changed file.
=> Fixes a bug in Java web server

stdlib/wyvern/collections/Collection.wyt
This pull request is sent to practice how to send a pull request. I only committed the Collection.wyt file, and hope it looks good.
=> Collection.wyt

.travis.yml, tools/src/wyvern/tools/tests/ModuleSystemTests.java, tools/src/wyvern/tools/tests/TestUtil.java, tools/src/wyvern/tools/tests/modules/arrowModuleClient1.wyv, tools/src/wyvern/tools/tests/modules/arrowModuleClient2.wyv, tools/src/wyvern/tools/tests/modules/arrowModuleImplementation1.wyv, tools/src/wyvern/tools/tests/modules/arrowModuleImplementation2.wyv, tools/src/wyvern/tools/typedAST/core/declarations/ModuleDeclaration.java
Supported arrow types in module defs. Added two test case in ModuleSystemTests.java.
=> Resolved issue #332, supported arrow types in module defs. Added two test case in ModuleSystemTests.java.

.gitignore, stdlib/wyvern/IfTSL.wyv, tools/src/wyvern/tools/tests/OIRTests.java
Modified regex for if and else statement in IfTSL.wyv to support commenting on if and else statement. Added testcases in OIRTests.java to test commenting on if and else. Modified .gitignore file to ignore tools/out.gradver.
=> Resolved issue #222, supported commenting on if and else statement. Added test cases in OIRTest.java.

tools/src/wyvern/target/oir/EmitPythonVisitor.java, tools/src/wyvern/tools/lexing/WyvernLexer.x
This bug has been present in the code since string literals were introduced in commit 763fb4f!!
=> Fix handling of octal escape sequences in string literals

selfhost/binding.wyv, selfhost/bound.wyv, selfhost/lambda.wyv, selfhost/raw.wyv, selfhost/typecheck.wyv, selfhost/types.wyv, selfhost/wyvernParser.wyv
This is the start of the typechecker. Unfortunately it can't really type anything interesting yet but more rules can be added soon
Also I have moved some type definitions to types.wyv due to issues with circular imports.
=> start of typechecker
